language: php
sudo: false

php:
  - 7.1

before_script:
  - curl -LSs https://box-project.github.io/box2/installer.php | php
  - composer install --no-interaction --no-progress

script:
  - ./box.phar build
  - sha1sum wp-cli.phar > wp-cli.version

deploy:
  provider: releases
  # Needed per https://stackoverflow.com/questions/41133548/how-to-fix-github-release-deployment-of-latex-project.
  skip_cleanup: true
  api_key:
    secure: iK5KHxOFD1Y8jNq78y+0shDZ+j+aiYpq6fzTfp0kMBO3+KqoHE+8gQXO3x1YhGt2vmfRS4+5W7b8N+FVEA4WQFljn1/iFIC36SmzAeAL9O1n8d+dpJ+A+xYPrj20TCMwi8Oap+2TzwDsx4I+V905b73BzdYo58PjXL7Rnb3Xdk+jeFipiGarCEA/nvzG4TTYMVWLEUNmgu0SMU4RpWUDVO+qHdXDPstyeiVlMdCR75JMgw0OBhacilgccZjHSS63AdUCnh1Kivi17L9GsSHAbEBITA+9z90vMWdZddbxSNjjsbkeh8q6Y1XXNgebQxSLpFxH9XaVP73vc4JdZXG7yMLBJMvA/dBi1cabZ3V2JkLzEovAb6IE6wJMyDzjf0W3TDLqMxzXIKCf3x0O7Y7pQ8pfc0IbfDidat/Iata/DI2+AYTF5Mc83ibf6dCq+RVyWCC5/ND+2rf6pOkZH62N9B9CvTzSGocqaYQUgk1HS/DMnw3BNIOan27e0EQNA88K4KZWPcVYaejyDnOyJ1GBm0qh6JORzJBirfkI6wcnDw1b23dBuztcT5jvJWoDHc0x9X8H57xjNK3ScTWlmkTWnMhm46A7YSFBpGdwX5fzORLo6UDp4zC+v1MlZpGnnXkfxZtd09oJibdh3WEU8wA+qQ3NUPtYjAhwKY+IiVgWhv8=
  file:
    - wp-cli.phar
    - wp-cli.version
  on:
    repo: drush-ops/drush-launcher
    tags: true
